import { MigrationInterface, QueryRunner } from "typeorm";

export class AddSuperAdminEntities1766845614387 implements MigrationInterface {
    name = 'AddSuperAdminEntities1766845614387'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "whatsapp_template_policies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL DEFAULT 'default', "allowedCategories" jsonb NOT NULL, "allowedLanguages" jsonb NOT NULL, "buttonTypes" jsonb NOT NULL, "mediaSupport" jsonb NOT NULL, "maxVariables" integer NOT NULL DEFAULT '10', "maxBodyLength" integer NOT NULL DEFAULT '1024', "maxHeaderLength" integer NOT NULL DEFAULT '60', "maxFooterLength" integer NOT NULL DEFAULT '60', "planRestrictions" jsonb NOT NULL, "blockedKeywords" jsonb, "blockedUrlDomains" jsonb, "validateBeforeSubmission" boolean NOT NULL DEFAULT true, "blockUrlShorteners" boolean NOT NULL DEFAULT true, "checkExcessiveCaps" boolean NOT NULL DEFAULT true, "maxCapsPercentage" integer NOT NULL DEFAULT '30', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_8992fae20774d2fdb7e73f7af19" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."conversation_pricing_category_enum" AS ENUM('marketing', 'utility', 'authentication', 'service')`);
        await queryRunner.query(`CREATE TABLE "conversation_pricing" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "countryCode" character varying(2) NOT NULL, "countryName" character varying(100), "category" "public"."conversation_pricing_category_enum" NOT NULL, "metaCostUsd" numeric(10,6) NOT NULL, "platformCredits" numeric(10,4) NOT NULL, "platformCurrencyAmount" numeric(10,4) NOT NULL, "platformCurrency" character varying(3) NOT NULL DEFAULT 'INR', "markupPercentage" numeric(5,2) NOT NULL DEFAULT '30', "isFree" boolean NOT NULL DEFAULT false, "effectiveFrom" date, "effectiveTo" date, "isActive" boolean NOT NULL DEFAULT true, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_0aa54e681495f83f2f694c3ecb3" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_143bc97610efd655fe1f300a68" ON "conversation_pricing" ("isActive") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_dfa8065b9e393c286980a6d7ac" ON "conversation_pricing" ("countryCode", "category") `);
        await queryRunner.query(`CREATE TYPE "public"."whatsapp_conversations_category_enum" AS ENUM('marketing', 'utility', 'authentication', 'service')`);
        await queryRunner.query(`CREATE TYPE "public"."whatsapp_conversations_windowstatus_enum" AS ENUM('open', 'closed', 'expired')`);
        await queryRunner.query(`CREATE TABLE "whatsapp_conversations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "contactId" uuid NOT NULL, "phoneNumberId" character varying(255) NOT NULL, "contactPhone" character varying(20) NOT NULL, "contactCountry" character varying(2), "metaConversationId" character varying(255), "category" "public"."whatsapp_conversations_category_enum" NOT NULL, "windowOpenedAt" TIMESTAMP NOT NULL, "windowExpiresAt" TIMESTAMP NOT NULL, "isWindowOpen" boolean NOT NULL DEFAULT true, "windowStatus" "public"."whatsapp_conversations_windowstatus_enum" NOT NULL DEFAULT 'open', "isBillable" boolean NOT NULL DEFAULT true, "creditsCost" numeric(10,4) NOT NULL DEFAULT '0', "currencyCost" numeric(10,4) NOT NULL DEFAULT '0', "metaCost" numeric(10,6), "billedAt" TIMESTAMP, "transactionId" uuid, "messageCount" integer NOT NULL DEFAULT '0', "inboundMessageCount" integer NOT NULL DEFAULT '0', "outboundMessageCount" integer NOT NULL DEFAULT '0', "initiatedBy" character varying(20) NOT NULL, "firstMessageId" uuid, "lastMessageId" uuid, "lastMessageAt" TIMESTAMP, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_2332059ecc247e8ae7931783c94" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e02165ce70044c4d310d60a18d" ON "whatsapp_conversations" ("isBillable") `);
        await queryRunner.query(`CREATE INDEX "IDX_c3d96b9c455310cbb3180bab63" ON "whatsapp_conversations" ("metaConversationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_e6b04a3c3570c7e66f546c97b7" ON "whatsapp_conversations" ("tenantId", "windowExpiresAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_cbde9e6752e2ce6ed29bb2cab3" ON "whatsapp_conversations" ("tenantId", "contactId", "isWindowOpen") `);
        await queryRunner.query(`CREATE TABLE "topup_packages" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "description" text, "badge" character varying(50), "credits" integer NOT NULL, "bonusCredits" integer NOT NULL DEFAULT '0', "price" numeric(10,2) NOT NULL, "currency" character varying(3) NOT NULL DEFAULT 'INR', "originalPrice" numeric(10,2), "savingsPercentage" integer NOT NULL DEFAULT '0', "isActive" boolean NOT NULL DEFAULT true, "isPopular" boolean NOT NULL DEFAULT false, "isBestValue" boolean NOT NULL DEFAULT false, "isHidden" boolean NOT NULL DEFAULT false, "minPurchaseCount" integer NOT NULL DEFAULT '1', "maxPurchaseCount" integer, "availableForPlans" jsonb, "creditsValidityDays" integer NOT NULL DEFAULT '0', "allowForAutoRecharge" boolean NOT NULL DEFAULT true, "promoStartDate" TIMESTAMP, "promoEndDate" TIMESTAMP, "promoCode" character varying(50), "sortOrder" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_de918041e597ba272731fb99ed8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d1a01aab13561136c4dc1e3f5c" ON "topup_packages" ("sortOrder") `);
        await queryRunner.query(`CREATE INDEX "IDX_a8ac73f216689d9fca0b5c4219" ON "topup_packages" ("isActive") `);
        await queryRunner.query(`CREATE TYPE "public"."admin_users_role_enum" AS ENUM('platform_admin', 'support', 'viewer')`);
        await queryRunner.query(`CREATE TYPE "public"."admin_users_status_enum" AS ENUM('active', 'inactive', 'suspended')`);
        await queryRunner.query(`CREATE TABLE "admin_users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying(255) NOT NULL, "passwordHash" character varying(255) NOT NULL, "firstName" character varying(100) NOT NULL, "lastName" character varying(100) NOT NULL, "role" "public"."admin_users_role_enum" NOT NULL DEFAULT 'support', "status" "public"."admin_users_status_enum" NOT NULL DEFAULT 'active', "permissions" jsonb, "avatarUrl" character varying(255), "phoneNumber" character varying(20), "lastLoginAt" TIMESTAMP, "lastLoginIp" character varying(45), "loginCount" integer NOT NULL DEFAULT '0', "twoFactorEnabled" boolean NOT NULL DEFAULT false, "twoFactorSecret" character varying(255), "passwordChangedAt" TIMESTAMP, "mustChangePassword" boolean NOT NULL DEFAULT false, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_dcd0c8a4b10af9c986e510b9ecc" UNIQUE ("email"), CONSTRAINT "PK_06744d221bb6145dc61e5dc441d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_dcd0c8a4b10af9c986e510b9ec" ON "admin_users" ("email") `);
        await queryRunner.query(`CREATE TYPE "public"."message_wallets_status_enum" AS ENUM('active', 'suspended', 'depleted')`);
        await queryRunner.query(`CREATE TABLE "message_wallets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "creditBalance" numeric(12,2) NOT NULL DEFAULT '0', "currencyBalance" numeric(12,2) NOT NULL DEFAULT '0', "currency" character varying(3) NOT NULL DEFAULT 'INR', "planCreditsMonthly" integer NOT NULL DEFAULT '0', "planCreditsUsed" integer NOT NULL DEFAULT '0', "planCreditsResetDate" date, "lowBalanceThreshold" integer NOT NULL DEFAULT '100', "lowBalanceAlertSent" boolean NOT NULL DEFAULT false, "lowBalanceAlertSentAt" TIMESTAMP, "autoRechargeEnabled" boolean NOT NULL DEFAULT false, "autoRechargeThreshold" integer NOT NULL DEFAULT '100', "autoRechargeAmount" numeric(10,2), "autoRechargePaymentMethodId" character varying(255), "autoRechargePackageId" uuid, "lastAutoRechargeAt" TIMESTAMP, "autoRechargeFailureCount" integer NOT NULL DEFAULT '0', "status" "public"."message_wallets_status_enum" NOT NULL DEFAULT 'active', "suspendedAt" TIMESTAMP, "suspendedReason" text, "totalCreditsAdded" integer NOT NULL DEFAULT '0', "totalCreditsUsed" integer NOT NULL DEFAULT '0', "totalConversations" integer NOT NULL DEFAULT '0', "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_1f3894957956ca3a5d1ca7ca9c9" UNIQUE ("tenantId"), CONSTRAINT "REL_1f3894957956ca3a5d1ca7ca9c" UNIQUE ("tenantId"), CONSTRAINT "PK_cb0e554b1950aed40872a10c75d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bb666003ab4036b83ae9f2923f" ON "message_wallets" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_1f3894957956ca3a5d1ca7ca9c" ON "message_wallets" ("tenantId") `);
        await queryRunner.query(`CREATE TYPE "public"."message_transactions_type_enum" AS ENUM('credit', 'debit', 'refund', 'plan_allocation', 'expiry', 'adjustment', 'bonus')`);
        await queryRunner.query(`CREATE TYPE "public"."message_transactions_paymentmethod_enum" AS ENUM('stripe', 'razorpay', 'paypal', 'bank_transfer', 'admin_credit', 'plan_credit')`);
        await queryRunner.query(`CREATE TYPE "public"."message_transactions_conversationtype_enum" AS ENUM('marketing', 'utility', 'authentication', 'service')`);
        await queryRunner.query(`CREATE TYPE "public"."message_transactions_status_enum" AS ENUM('pending', 'completed', 'failed', 'refunded', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "message_transactions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenantId" uuid NOT NULL, "walletId" uuid NOT NULL, "type" "public"."message_transactions_type_enum" NOT NULL, "topUpPackageId" uuid, "paymentId" character varying(255), "paymentMethod" "public"."message_transactions_paymentmethod_enum", "paymentGatewayResponse" character varying(255), "conversationType" "public"."message_transactions_conversationtype_enum", "messageId" uuid, "conversationId" uuid, "contactId" uuid, "contactCountry" character varying(2), "creditsAmount" numeric(12,2) NOT NULL, "currencyAmount" numeric(12,2), "metaCost" numeric(10,4), "platformMarkup" numeric(10,4), "balanceBefore" numeric(12,2) NOT NULL, "balanceAfter" numeric(12,2) NOT NULL, "status" "public"."message_transactions_status_enum" NOT NULL DEFAULT 'pending', "failureReason" text, "relatedTransactionId" uuid, "description" character varying(255), "metadata" jsonb, "adjustedByAdminId" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_380864a8ebbae051c3d2e46acec" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d228a1939cd3f36f7cb6495f10" ON "message_transactions" ("conversationId") `);
        await queryRunner.query(`CREATE INDEX "IDX_d6383bd1037034c5e869090ad1" ON "message_transactions" ("paymentId") `);
        await queryRunner.query(`CREATE INDEX "IDX_266293e8df1a39928be33ee541" ON "message_transactions" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_505160257588e00488b5371fd4" ON "message_transactions" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_38d2790445115e6a669d8d496b" ON "message_transactions" ("walletId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c264de0d4273cc94cf95994c0e" ON "message_transactions" ("tenantId", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."feature_flags_type_enum" AS ENUM('boolean', 'plan_gated', 'percentage', 'tenant_list')`);
        await queryRunner.query(`CREATE TABLE "feature_flags" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "key" character varying(100) NOT NULL, "name" character varying(255) NOT NULL, "description" text, "category" character varying(50), "type" "public"."feature_flags_type_enum" NOT NULL DEFAULT 'boolean', "defaultValue" boolean NOT NULL DEFAULT false, "planOverrides" jsonb, "rolloutPercentage" integer NOT NULL DEFAULT '0', "tenantWhitelist" jsonb, "tenantBlacklist" jsonb, "isActive" boolean NOT NULL DEFAULT true, "metadata" jsonb, "createdById" uuid, "updatedById" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_36d0344370584b4d6a953c53a69" UNIQUE ("key"), CONSTRAINT "PK_db657d344e9caacfc9d5cf8bbac" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_bfd7aaa3936170819a3c6c169b" ON "feature_flags" ("isActive") `);
        await queryRunner.query(`CREATE INDEX "IDX_bee0352477ad519ff7dfcdc30f" ON "feature_flags" ("category") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_36d0344370584b4d6a953c53a6" ON "feature_flags" ("key") `);
        await queryRunner.query(`CREATE TABLE "automation_policies" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(255) NOT NULL DEFAULT 'default', "description" text, "globalEnabled" boolean NOT NULL DEFAULT true, "globalKillSwitch" boolean NOT NULL DEFAULT false, "killSwitchActivatedAt" TIMESTAMP, "killSwitchReason" character varying(255), "killSwitchActivatedBy" uuid, "planLimits" jsonb NOT NULL, "allowedTriggers" jsonb NOT NULL, "allowedActions" jsonb NOT NULL, "blockSettings" jsonb NOT NULL, "safetyControls" jsonb NOT NULL, "lastUpdatedBy" uuid, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_3aa47d01dcdb556e9ec656b8060" UNIQUE ("name"), CONSTRAINT "PK_c7460647cef92d467d443941769" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_3aa47d01dcdb556e9ec656b806" ON "automation_policies" ("name") `);
        await queryRunner.query(`CREATE TYPE "public"."admin_audit_logs_action_enum" AS ENUM('login', 'logout', 'password_change', 'create', 'read', 'update', 'delete', 'activate', 'deactivate', 'suspend', 'unsuspend', 'approve', 'reject', 'pause', 'resume', 'credit_issue', 'refund', 'pricing_change', 'kill_switch', 'feature_toggle', 'policy_change', 'export', 'import')`);
        await queryRunner.query(`CREATE TABLE "admin_audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "adminId" uuid, "adminEmail" character varying(255), "adminName" character varying(100), "action" "public"."admin_audit_logs_action_enum" NOT NULL, "resourceType" character varying(50) NOT NULL, "resourceId" uuid, "resourceName" character varying(255), "targetTenantId" uuid, "targetTenantName" character varying(255), "previousValues" jsonb, "newValues" jsonb, "ipAddress" character varying(45), "userAgent" text, "httpMethod" character varying(10), "requestPath" character varying(500), "description" text, "metadata" jsonb, "success" boolean NOT NULL DEFAULT true, "errorMessage" text, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_de7a8fc2fbb525484c71a86bb96" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_48ba6918107ce003d42714dc2f" ON "admin_audit_logs" ("resourceId") `);
        await queryRunner.query(`CREATE INDEX "IDX_c9b746f627d2fae1148b4536c6" ON "admin_audit_logs" ("resourceType", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_13cafaf0d4501d0346888efc66" ON "admin_audit_logs" ("action", "createdAt") `);
        await queryRunner.query(`CREATE INDEX "IDX_f9f36bfd0c64d8f4ad75e30e10" ON "admin_audit_logs" ("adminId", "createdAt") `);
        await queryRunner.query(`CREATE TYPE "public"."carrier_connections_carrier_enum" AS ENUM('delhivery', 'shiprocket', 'bluedart', 'dtdc', 'ecom_express', 'xpressbees', 'shadowfax', 'custom')`);
        await queryRunner.query(`CREATE TABLE "carrier_connections" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "carrier" "public"."carrier_connections_carrier_enum" NOT NULL, "name" character varying NOT NULL, "api_key" text, "api_secret" text, "account_id" character varying, "webhook_secret" character varying, "base_url" character varying, "is_active" boolean NOT NULL DEFAULT true, "is_default" boolean NOT NULL DEFAULT false, "settings" jsonb, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d43a266f996750f53931eec735c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_11a73944213c0a56037bf142dc" ON "carrier_connections" ("tenant_id", "carrier") `);
        await queryRunner.query(`CREATE TYPE "public"."shipments_carrier_enum" AS ENUM('delhivery', 'shiprocket', 'bluedart', 'dtdc', 'ecom_express', 'xpressbees', 'shadowfax', 'custom')`);
        await queryRunner.query(`CREATE TYPE "public"."shipments_status_enum" AS ENUM('created', 'picked_up', 'in_transit', 'out_for_delivery', 'delivered', 'failed_delivery', 'rto_initiated', 'rto_delivered', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "shipments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" character varying NOT NULL, "order_id" character varying NOT NULL, "carrier_id" character varying, "carrier" "public"."shipments_carrier_enum" NOT NULL, "tracking_number" character varying NOT NULL, "awb_number" character varying, "status" "public"."shipments_status_enum" NOT NULL DEFAULT 'created', "status_message" character varying, "weight" numeric(10,2), "dimensions" jsonb, "shipping_cost" numeric(10,2), "current_location" character varying, "expected_delivery" TIMESTAMP, "tracking_history" jsonb NOT NULL DEFAULT '[]', "delivery_attempts" integer NOT NULL DEFAULT '0', "last_attempt_at" TIMESTAMP, "last_attempt_reason" character varying, "is_rto" boolean NOT NULL DEFAULT false, "rto_reason" character varying, "rto_initiated_at" TIMESTAMP, "shipped_at" TIMESTAMP, "picked_up_at" TIMESTAMP, "delivered_at" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6deda4532ac542a93eab214b564" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e86fac2a18a75dcb82bfbb23f4" ON "shipments" ("order_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_e148d569550cfa0295ccf23706" ON "shipments" ("tracking_number") `);
        await queryRunner.query(`CREATE INDEX "IDX_3273d2253c9dc1f6e58cbfa926" ON "shipments" ("tenant_id", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."product_recommendations_type_enum" AS ENUM('upsell', 'cross_sell', 'reorder', 'frequently_bought_together', 'similar_products', 'trending', 'personalized')`);
        await queryRunner.query(`CREATE TABLE "product_recommendations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" uuid NOT NULL, "type" "public"."product_recommendations_type_enum" NOT NULL, "source_product_id" character varying, "source_category" character varying, "recommended_product_id" character varying NOT NULL, "recommended_product_name" character varying NOT NULL, "recommended_product_image" character varying, "recommended_product_price" numeric(10,2) NOT NULL, "score" numeric(5,4) NOT NULL DEFAULT '0', "display_order" integer NOT NULL DEFAULT '0', "is_active" boolean NOT NULL DEFAULT true, "impressions" integer NOT NULL DEFAULT '0', "clicks" integer NOT NULL DEFAULT '0', "conversions" integer NOT NULL DEFAULT '0', "revenue" numeric(10,2) NOT NULL DEFAULT '0', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_34c228b0d96e8ff52db667b4c22" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_042bacdb524981bf4da6eb412d" ON "product_recommendations" ("source_product_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b560bbadfe4bb9f1e362118a0a" ON "product_recommendations" ("tenant_id", "type") `);
        await queryRunner.query(`CREATE TYPE "public"."reorder_reminders_status_enum" AS ENUM('pending', 'sent', 'clicked', 'converted', 'dismissed', 'snoozed')`);
        await queryRunner.query(`CREATE TABLE "reorder_reminders" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tenant_id" character varying NOT NULL, "contact_id" character varying NOT NULL, "product_id" character varying NOT NULL, "product_name" character varying NOT NULL, "product_image" character varying, "last_order_id" character varying NOT NULL, "last_order_date" TIMESTAMP NOT NULL, "estimated_reorder_date" TIMESTAMP NOT NULL, "reorder_cycle_days" integer NOT NULL DEFAULT '30', "status" "public"."reorder_reminders_status_enum" NOT NULL DEFAULT 'pending', "reminder_count" integer NOT NULL DEFAULT '0', "last_reminded_at" TIMESTAMP, "converted_order_id" character varying, "snoozed_until" TIMESTAMP, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_80532b4eb80341eaa7654e23ba9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_75e972da6b9418b8b0af8eca79" ON "reorder_reminders" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_b288427aac5e7e3453cb7e3bd5" ON "reorder_reminders" ("tenant_id", "contact_id") `);
        await queryRunner.query(`ALTER TABLE "whatsapp_conversations" ADD CONSTRAINT "FK_03e82d2293677c8c6566c524bbc" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "whatsapp_conversations" ADD CONSTRAINT "FK_6fb1b9673490b045dfced94862e" FOREIGN KEY ("contactId") REFERENCES "contacts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_wallets" ADD CONSTRAINT "FK_1f3894957956ca3a5d1ca7ca9c9" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_transactions" ADD CONSTRAINT "FK_261d5c6ea8eaea9933c02b2dd28" FOREIGN KEY ("tenantId") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message_transactions" ADD CONSTRAINT "FK_38d2790445115e6a669d8d496bb" FOREIGN KEY ("walletId") REFERENCES "message_wallets"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feature_flags" ADD CONSTRAINT "FK_e5353786d6846781da29ecf7916" FOREIGN KEY ("createdById") REFERENCES "admin_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feature_flags" ADD CONSTRAINT "FK_1d946f6a10e44a1fd49e328ec37" FOREIGN KEY ("updatedById") REFERENCES "admin_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_audit_logs" ADD CONSTRAINT "FK_a139edf85d191fb20890356d734" FOREIGN KEY ("adminId") REFERENCES "admin_users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "carrier_connections" ADD CONSTRAINT "FK_2d4a8ced6ebc3cb0c506d97207a" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_recommendations" ADD CONSTRAINT "FK_92d96644ca7e8a9406ab95f8d94" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "product_recommendations" DROP CONSTRAINT "FK_92d96644ca7e8a9406ab95f8d94"`);
        await queryRunner.query(`ALTER TABLE "carrier_connections" DROP CONSTRAINT "FK_2d4a8ced6ebc3cb0c506d97207a"`);
        await queryRunner.query(`ALTER TABLE "admin_audit_logs" DROP CONSTRAINT "FK_a139edf85d191fb20890356d734"`);
        await queryRunner.query(`ALTER TABLE "feature_flags" DROP CONSTRAINT "FK_1d946f6a10e44a1fd49e328ec37"`);
        await queryRunner.query(`ALTER TABLE "feature_flags" DROP CONSTRAINT "FK_e5353786d6846781da29ecf7916"`);
        await queryRunner.query(`ALTER TABLE "message_transactions" DROP CONSTRAINT "FK_38d2790445115e6a669d8d496bb"`);
        await queryRunner.query(`ALTER TABLE "message_transactions" DROP CONSTRAINT "FK_261d5c6ea8eaea9933c02b2dd28"`);
        await queryRunner.query(`ALTER TABLE "message_wallets" DROP CONSTRAINT "FK_1f3894957956ca3a5d1ca7ca9c9"`);
        await queryRunner.query(`ALTER TABLE "whatsapp_conversations" DROP CONSTRAINT "FK_6fb1b9673490b045dfced94862e"`);
        await queryRunner.query(`ALTER TABLE "whatsapp_conversations" DROP CONSTRAINT "FK_03e82d2293677c8c6566c524bbc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b288427aac5e7e3453cb7e3bd5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_75e972da6b9418b8b0af8eca79"`);
        await queryRunner.query(`DROP TABLE "reorder_reminders"`);
        await queryRunner.query(`DROP TYPE "public"."reorder_reminders_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b560bbadfe4bb9f1e362118a0a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_042bacdb524981bf4da6eb412d"`);
        await queryRunner.query(`DROP TABLE "product_recommendations"`);
        await queryRunner.query(`DROP TYPE "public"."product_recommendations_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3273d2253c9dc1f6e58cbfa926"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e148d569550cfa0295ccf23706"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e86fac2a18a75dcb82bfbb23f4"`);
        await queryRunner.query(`DROP TABLE "shipments"`);
        await queryRunner.query(`DROP TYPE "public"."shipments_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."shipments_carrier_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_11a73944213c0a56037bf142dc"`);
        await queryRunner.query(`DROP TABLE "carrier_connections"`);
        await queryRunner.query(`DROP TYPE "public"."carrier_connections_carrier_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f9f36bfd0c64d8f4ad75e30e10"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_13cafaf0d4501d0346888efc66"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c9b746f627d2fae1148b4536c6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_48ba6918107ce003d42714dc2f"`);
        await queryRunner.query(`DROP TABLE "admin_audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."admin_audit_logs_action_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3aa47d01dcdb556e9ec656b806"`);
        await queryRunner.query(`DROP TABLE "automation_policies"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_36d0344370584b4d6a953c53a6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bee0352477ad519ff7dfcdc30f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bfd7aaa3936170819a3c6c169b"`);
        await queryRunner.query(`DROP TABLE "feature_flags"`);
        await queryRunner.query(`DROP TYPE "public"."feature_flags_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c264de0d4273cc94cf95994c0e"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_38d2790445115e6a669d8d496b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_505160257588e00488b5371fd4"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_266293e8df1a39928be33ee541"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d6383bd1037034c5e869090ad1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d228a1939cd3f36f7cb6495f10"`);
        await queryRunner.query(`DROP TABLE "message_transactions"`);
        await queryRunner.query(`DROP TYPE "public"."message_transactions_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."message_transactions_conversationtype_enum"`);
        await queryRunner.query(`DROP TYPE "public"."message_transactions_paymentmethod_enum"`);
        await queryRunner.query(`DROP TYPE "public"."message_transactions_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1f3894957956ca3a5d1ca7ca9c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_bb666003ab4036b83ae9f2923f"`);
        await queryRunner.query(`DROP TABLE "message_wallets"`);
        await queryRunner.query(`DROP TYPE "public"."message_wallets_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dcd0c8a4b10af9c986e510b9ec"`);
        await queryRunner.query(`DROP TABLE "admin_users"`);
        await queryRunner.query(`DROP TYPE "public"."admin_users_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."admin_users_role_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a8ac73f216689d9fca0b5c4219"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d1a01aab13561136c4dc1e3f5c"`);
        await queryRunner.query(`DROP TABLE "topup_packages"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cbde9e6752e2ce6ed29bb2cab3"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e6b04a3c3570c7e66f546c97b7"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c3d96b9c455310cbb3180bab63"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e02165ce70044c4d310d60a18d"`);
        await queryRunner.query(`DROP TABLE "whatsapp_conversations"`);
        await queryRunner.query(`DROP TYPE "public"."whatsapp_conversations_windowstatus_enum"`);
        await queryRunner.query(`DROP TYPE "public"."whatsapp_conversations_category_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dfa8065b9e393c286980a6d7ac"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_143bc97610efd655fe1f300a68"`);
        await queryRunner.query(`DROP TABLE "conversation_pricing"`);
        await queryRunner.query(`DROP TYPE "public"."conversation_pricing_category_enum"`);
        await queryRunner.query(`DROP TABLE "whatsapp_template_policies"`);
    }

}
